- name: Demo on ignore_errors
  hosts: all
  tasks:
    - name: Check dpkg command is there or not 
      shell: which dpkg 
      register: out 
      ignore_errors: yes

    - name: find kernel rpm version 
      shell: dpkg --list | grep kernel 
      when: out.rc == 0